POST http://localhost:8080/api/roles HTTP/1.1
content-type: application/json;charset=UTF-8


{"nombre":"sargento"}

###
//GET /roles
GET http://localhost:8080/api/roles HTTP/1.1

###
//GET /roles/1
GET http://localhost:8080/api/roles/1 HTTP/1.1

###
//PUT /roles/1
PUT http://localhost:8080/api/roles/1 HTTP/1.1

###
//DELETE /roles/1
GET http://localhost:8080/api/roles/1 HTTP/1.1
