module.exports = {
  Activity:require('./Activity.js'),
  Commerce: require("./Commerce.js"),
  Company: require("./Company.js"),
  Event: require("./Event.js"),
  Inscription: require("./Inscription.js"),
  Mode: require("./Mode.js"),
  Promotion: require("./Promotion.js"),
  Province: require("./Province.js"),
  Ranking:require('./Ranking.js'),
  Rol: require("./Rol.js"),
  Token: require("./Token.js"),
  User: require("./User.js"),
  UserPromo: require("./UserPromo.js"),
  // Extra: require("./extra.js"),
  // Categorias: require("./Categorias.js"),
  // Usu_comercio: require("./Usuario_Comercio.js"),
};
